# Generated by Django 4.1.1 on 2022-10-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mis',
            name='consignorlocation',
            field=models.TextField(blank=True, db_column='Consignor Location', null=True),
        ),
        migrations.AlterField(
            model_name='mis',
            name='deliverydate',
            field=models.TextField(blank=True, db_column='Delivery Date', null=True),
        ),
        migrations.AlterField(
            model_name='mis',
            name='location',
            field=models.TextField(blank=True, db_column='Location', null=True),
        ),
    ]
