# Generated by Django 4.1.2 on 2022-10-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_lecidump'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecidump',
            name='id',
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='lecino',
            field=models.IntegerField(db_column='LECINo', default=1, primary_key=True, serialize=False),
        ),
    ]
