# Generated by Django 4.1.2 on 2022-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_lecidump_id_alter_lecidump_lecino'),
    ]

    
