# Generated by Django 4.1.2 on 2022-10-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_lecidump_checkpoint_alter_lecidump_chkindate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrnDump',
            fields=[
                ('materialdocument', models.IntegerField(db_column='MaterialDocument', primary_key=True, serialize=False)),
                ('material', models.IntegerField(blank=True, db_column='Material', null=True)),
                ('materialdescription', models.TextField(blank=True, db_column='MaterialDescription', null=True)),
                ('reference', models.TextField(blank=True, db_column='Reference', null=True)),
                ('inv_dt_field', models.TextField(blank=True, db_column='Inv.Dt.', null=True)),
                ('grqty_field', models.IntegerField(blank=True, db_column='GRQty.', null=True)),
                ('mb02qty_field', models.IntegerField(blank=True, db_column='MB02Qty.', null=True)),
                ('mov', models.IntegerField(blank=True, db_column='Mov', null=True)),
                ('strloc_field', models.TextField(blank=True, db_column='StrLoc.', null=True)),
                ('leci', models.IntegerField(blank=True, db_column='LECI', null=True)),
                ('purchaseorder', models.IntegerField(blank=True, db_column='PurchaseOrder', null=True)),
                ('vendor', models.TextField(blank=True, db_column='Vendor', null=True)),
                ('postingdate', models.TextField(blank=True, db_column='PostingDate', null=True)),
                ('plant', models.IntegerField(blank=True, db_column='Plant', null=True)),
                ('grnamount', models.IntegerField(blank=True, db_column='GRNAmount', null=True)),
                ('vendorname', models.TextField(blank=True, db_column='VendorName', null=True)),
            ],
            options={
                'db_table': 'Grn Dump',
                'managed': True,
            },
        ),
    ]
