# Generated by Django 4.1.2 on 2022-10-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_grndump'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMaster',
            fields=[
                ('vendor', models.TextField(db_column='Vendor', primary_key=True, serialize=False)),
                ('vendordescription', models.TextField(blank=True, db_column='VENDORDESCRIPTION', null=True)),
                ('name3', models.TextField(blank=True, db_column='Name3', null=True)),
                ('name4', models.TextField(blank=True, db_column='Name4', null=True)),
                ('city', models.TextField(blank=True, db_column='City', null=True)),
                ('postalcode', models.IntegerField(blank=True, db_column='PostalCode', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('recovery', models.TextField(blank=True, db_column='Recovery', null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
            ],
            options={
                'db_table': 'Vendor Master',
                'managed': True,
            },
        ),
        
    ]
