# Generated by Django 4.1.2 on 2022-10-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_vendormaster_alter_grndump_grnamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.IntegerField(blank=True, db_column='Material', null=True)),
                ('materialdescription', models.TextField(blank=True, db_column='Materialdescription', null=True)),
                ('vendorcode', models.TextField(blank=True, db_column='VendorCode', null=True)),
                ('vendordescription', models.TextField(blank=True, db_column='VendorDescription', null=True)),
                ('quotavalidfrom', models.TextField(blank=True, db_column='QuotaValidfrom', null=True)),
                ('quotavalidto', models.TextField(blank=True, db_column='QuotaValidto', null=True)),
                ('quota_field', models.IntegerField(blank=True, db_column='Quota%', null=True)),
                ('quotanumber', models.IntegerField(blank=True, db_column='QuotaNumber', null=True)),
                ('proctype', models.TextField(blank=True, db_column='ProcType', null=True)),
                ('splproctype', models.TextField(blank=True, db_column='SplProcType', null=True)),
                ('bulkind', models.TextField(blank=True, db_column='BulkInd', null=True)),
                ('mrpcntrl', models.IntegerField(blank=True, db_column='MRPCntrl', null=True)),
            ],
            options={
                'db_table': 'Part Master',
                'managed': True,
            },
        ),
       
    ]
