# Generated by Django 4.1.2 on 2022-10-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_partmaster_alter_grndump_grnamount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partmaster',
            name='id',
        ),
        
    ]
