# Generated by Django 4.1.2 on 2022-11-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_remove_partmaster_id_alter_grndump_grnamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grndump',
            name='grnamount',
            field=models.IntegerField(blank=True, db_column='GRN Amount', null=True),
        ),
        migrations.AlterField(
            model_name='grndump',
            name='grqty_field',
            field=models.IntegerField(blank=True, db_column='GR Qty.', null=True),
        ),
        migrations.AlterField(
            model_name='grndump',
            name='inv_dt_field',
            field=models.TextField(blank=True, db_column='Inv. Dt.', null=True),
        ),
        migrations.AlterField(
            model_name='grndump',
            name='materialdescription',
            field=models.TextField(blank=True, db_column='Material Description', null=True),
        ),
        migrations.AlterField(
            model_name='grndump',
            name='materialdocument',
            field=models.IntegerField(db_column='Material Document', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grndump',
            name='mb02qty_field',
            field=models.IntegerField(blank=True, db_column='MB02 Qty.', null=True),
        ),
        migrations.AlterField(
            model_name='grndump',
            name='postingdate',
            field=models.TextField(blank=True, db_column='Posting Date', null=True),
        ),
        migrations.AlterField(
            model_name='grndump',
            name='purchaseorder',
            field=models.IntegerField(blank=True, db_column='Purchase Order', null=True),
        ),
        migrations.AlterField(
            model_name='grndump',
            name='strloc_field',
            field=models.TextField(blank=True, db_column='Str Loc.', null=True),
        ),
        migrations.AlterField(
            model_name='grndump',
            name='vendorname',
            field=models.TextField(blank=True, db_column='Vendor Name', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='checkpoint',
            field=models.TextField(blank=True, db_column='Check Point', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='chkindate',
            field=models.TextField(blank=True, db_column='Chkin Date', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='chktime',
            field=models.TextField(blank=True, db_column='Chk Time', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='considerlspname',
            field=models.TextField(blank=True, db_column='Consider LSP Name', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='firstname',
            field=models.TextField(blank=True, db_column='First Name', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='lastname',
            field=models.TextField(blank=True, db_column='Last Name', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='lecino',
            field=models.IntegerField(db_column='LECI No', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='outby',
            field=models.TextField(blank=True, db_column='Out by', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='outdate',
            field=models.TextField(blank=True, db_column='Out date', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='outtime',
            field=models.TextField(blank=True, db_column='Out time', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='reldate',
            field=models.TextField(blank=True, db_column='Rel Date', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='releaseby',
            field=models.TextField(blank=True, db_column='Release by', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='reltime',
            field=models.TextField(blank=True, db_column='Rel Time', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='rfidno',
            field=models.IntegerField(blank=True, db_column='RFID No', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='textforloading',
            field=models.TextField(blank=True, db_column='Text for Loading', null=True),
        ),
        migrations.AlterField(
            model_name='lecidump',
            name='trucks_carslicenseplateno_field',
            field=models.TextField(blank=True, db_column="Truck's/Car's License Plate No.", null=True),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='bulkind',
            field=models.TextField(blank=True, db_column='Bulk Ind', null=True),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='material',
            field=models.IntegerField(db_column='Material', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='materialdescription',
            field=models.TextField(blank=True, db_column='Material description', null=True),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='mrpcntrl',
            field=models.IntegerField(blank=True, db_column='MRP Cntrl', null=True),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='proctype',
            field=models.TextField(blank=True, db_column='Proc Type', null=True),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='quota_field',
            field=models.IntegerField(blank=True, db_column='Quota %', null=True),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='quotanumber',
            field=models.IntegerField(blank=True, db_column='Quota Number', null=True),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='quotavalidfrom',
            field=models.TextField(blank=True, db_column='Quota Valid from', null=True),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='quotavalidto',
            field=models.TextField(blank=True, db_column='Quota Valid to', null=True),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='splproctype',
            field=models.TextField(blank=True, db_column='Spl Proc Type', null=True),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='vendorcode',
            field=models.TextField(blank=True, db_column='Vendor Code', null=True),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='vendordescription',
            field=models.TextField(blank=True, db_column='Vendor Description', null=True),
        ),
        migrations.AlterField(
            model_name='vendormaster',
            name='name3',
            field=models.TextField(blank=True, db_column='Name 3', null=True),
        ),
        migrations.AlterField(
            model_name='vendormaster',
            name='name4',
            field=models.TextField(blank=True, db_column='Name 4', null=True),
        ),
        migrations.AlterField(
            model_name='vendormaster',
            name='postalcode',
            field=models.IntegerField(blank=True, db_column='Postal Code', null=True),
        ),
        migrations.AlterField(
            model_name='vendormaster',
            name='vendordescription',
            field=models.TextField(blank=True, db_column='VENDOR DESCRIPTION', null=True),
        ),
    ]
