# Generated by Django 4.1.2 on 2022-11-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_grndump_grnamount_alter_grndump_grqty_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisFull',
            fields=[
                ('transporter_name', models.TextField(blank=True, db_column='Transporter Name', null=True)),
                ('activity_from_manual_vinsum_mis_field', models.TextField(blank=True, db_column='Activity (from manual-Vinsum MIS)', null=True)),
                ('payment_type_from_master_field', models.TextField(blank=True, db_column='PAYMENT TYPE (from master)', null=True)),
                ('activity_status', models.TextField(blank=True, db_column='Activity Status', null=True)),
                ('location', models.TextField(blank=True, db_column='Location', null=True)),
                ('delivery_date', models.TextField(blank=True, db_column='Delivery Date', null=True)),
                ('grn_number', models.BigIntegerField(blank=True, db_column='Grn Number', null=True)),
                ('lr_no_field', models.BigIntegerField(blank=True, db_column='LR no.', null=True)),
                ('lr_dt_field', models.TextField(blank=True, db_column='LR dt.', null=True)),
                ('lr_time', models.TextField(blank=True, db_column='LR Time', null=True)),
                ('consignor', models.TextField(blank=True, db_column='Consignor', null=True)),
                ('consignee', models.TextField(blank=True, db_column='Consignee', null=True)),
                ('consignor_location', models.TextField(blank=True, db_column='Consignor Location', null=True)),
                ('location_code', models.TextField(blank=True, db_column='Location Code', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('invoice_no_field', models.TextField(db_column='Invoice No.', primary_key=True, serialize=False)),
                ('invoice_date', models.TextField(blank=True, db_column='Invoice Date', null=True)),
                ('vendor_po_no', models.TextField(blank=True, db_column='Vendor PO No', null=True)),
                ('part_no_field', models.TextField(blank=True, db_column='Part No.', null=True)),
                ('pkg', models.BigIntegerField(blank=True, db_column='PKG', null=True)),
                ('pkg_type', models.TextField(blank=True, db_column='PKG TYPE', null=True)),
                ('qty_field', models.BigIntegerField(blank=True, db_column='Qty.', null=True)),
                ('actual_wt_kg_field', models.TextField(blank=True, db_column='Actual Wt. (KG)', null=True)),
                ('material_document', models.BigIntegerField(blank=True, db_column='Material Document', null=True)),
                ('material', models.TextField(blank=True, db_column='Material', null=True)),
                ('material_description', models.TextField(blank=True, db_column='Material Description', null=True)),
                ('reference', models.TextField(blank=True, db_column='Reference', null=True)),
                ('inv_dt_field', models.TextField(blank=True, db_column='Inv. Dt.', null=True)),
                ('gr_qty_field', models.TextField(blank=True, db_column='GR Qty.', null=True)),
                ('mb02_qty_field', models.TextField(blank=True, db_column='MB02 Qty.', null=True)),
                ('mov', models.TextField(blank=True, db_column='Mov', null=True)),
                ('str_loc_field', models.TextField(blank=True, db_column='Str Loc.', null=True)),
                ('leci', models.TextField(blank=True, db_column='LECI', null=True)),
                ('purchase_order', models.TextField(blank=True, db_column='Purchase Order', null=True)),
                ('vendor', models.TextField(blank=True, db_column='Vendor', null=True)),
                ('posting_date', models.TextField(blank=True, db_column='Posting Date', null=True)),
                ('plant', models.TextField(blank=True, db_column='Plant', null=True)),
                ('grn_amount', models.TextField(blank=True, db_column='GRN Amount', null=True)),
                ('vendor_name', models.TextField(blank=True, db_column='Vendor Name', null=True)),
            ],
            options={
                'db_table': 'MIS FULL',
                'managed': False,
            },
        ),
    ]
